### ISSUE TITLE
Epic: Create Box components

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype#145]
**Problem**
In order to display different structural elements like forms or tables, rap uses "Box" components. These components were constructed in AngularJS but do not work with the latest version of Angular.

**Solution**
Recreate the "Box" components in the latest version of Angular.

**Tasks**
Create the following components:

- [x] AmpersandTarski/prototype-frontend#23
- [x] AmpersandTarski/prototype-frontend#24
- [ ] AmpersandTarski/prototype#144
- [x] AmpersandTarski/prototype-frontend#26
- [x] AmpersandTarski/prototype-frontend#27
- [x] AmpersandTarski/prototype-frontend#28
- [x] AmpersandTarski/prototype-frontend#29

- [x] AmpersandTarski/prototype-frontend#116
