### ISSUE TITLE
Epic: Create View components

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype#146]
Problem
In order to display user defined views, rap uses "View" components. These components were constructed in AngularJS but do not work with the latest version of Angular.

Solution
Recreate the "View" components in the latest version of Angular.

Tasks
Create the following components:
- [x] AmpersandTarski/prototype-frontend#18
- [x] AmpersandTarski/prototype-frontend#19
- [x] AmpersandTarski/prototype-frontend#20
- [x] AmpersandTarski/prototype-frontend#21
- [x] AmpersandTarski/prototype-frontend#22

- [x] AmpersandTarski/prototype-frontend#115
